worker_processes auto;

load_module modules/ngx_http_brotli_filter_module.so;
# load_module modules/ngx_http_brotli_static_module.so;

error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 512;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '[$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';
    access_log /var/log/nginx/access.log main;

    add_header X-Frame-Options SAMEORIGIN;

    brotli on;
    brotli_comp_level 4;
    brotli_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    client_max_body_size 80M;
    server_tokens off;

    absolute_redirect off;
    port_in_redirect off;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay off;
    keepalive_timeout 65;

    include /etc/nginx/conf.d/*.conf;
}
