server {
  listen 80;
  server_name homepage;

  root /usr/share/nginx/html;
  index index.html index.htm;

  error_page 404 /404/;

  # Cache favicon 
  location = /favicon.svg {
    expires 15m;
    add_header Cache-Control "public";
    add_header Vary Accept-Encoding;
  }

  # Cache assets
  location ~* \.(jpg|jpeg|png|gif|ico|svg|webp|bmp|tiff|js)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    add_header Vary Accept-Encoding;
  }
}
