---
name: Lighthouse CI test
on:
  workflow_dispatch:
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
      - run: npm install -g @lhci/cli@0.15.x
      - run: lhci autorun
